# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
# Code generated from OpenTelemetry GenAI semantic conventions. DO NOT EDIT.

from typing import Final

RPC_RESPONSE_STATUS_CODE: Final[str] = "rpc.response.status_code"
"""Status code of the RPC returned by the RPC server or generated by the client
Usually it represents an error code, but may also represent partial success, warning, or differentiate between various types of successful outcomes.
Semantic conventions for individual RPC frameworks SHOULD document what `rpc.response.status_code` means in the context of that system and which values are considered to represent errors."""


__all__ = [
    "RPC_RESPONSE_STATUS_CODE",
]
