# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

"""Transparent proxy for ``with_raw_response`` / ``with_streaming_response`` results.

Client SDKs generated by Stainless (OpenAI's and Anthropic's among them) expose
``with_raw_response`` and ``with_streaming_response`` accessors that return an
HTTP-level response object instead of the parsed payload. The caller reads
metadata off it -- ``headers``, ``request_id``, ``http_response`` -- and calls
``parse()`` when it wants the payload, which may never happen.

``RawResponseProxy`` keeps the invocation open across that deferral and
finalizes it on whichever path the caller actually takes. Instrumentations
subclass it and supply the three SDK-specific pieces: how to read telemetry out
of an already-read body, how to read it out of a parsed payload, and how to wrap
a parsed stream.
"""

from __future__ import annotations

import functools
import inspect
import logging
from abc import ABCMeta, abstractmethod
from collections.abc import Awaitable, Callable
from typing import TYPE_CHECKING, Any, Protocol, TypeVar, cast

from opentelemetry.util.genai.stream import is_async_stream_wrapper

if TYPE_CHECKING:
    from opentelemetry.util.genai.invocation import GenAIInvocation

    class _ObjectProxy:
        __wrapped__: Any

        def __init__(self, wrapped: object) -> None: ...

else:
    from wrapt import ObjectProxy as _ObjectProxy

_logger = logging.getLogger(__name__)

ProxyT = TypeVar("ProxyT", bound="RawResponseProxy")


class _Closable(Protocol):
    """A stream wrapper the close hook can drive to completion."""

    def close(self) -> None: ...


class RawResponse(Protocol):
    """The shape of an SDK ``with_raw_response`` result.

    Structural rather than nominal: the SDKs' response classes
    (``LegacyAPIResponse``, ``APIResponse``, ``AsyncAPIResponse``) all match,
    but they live in private modules, so matching on shape keeps this working
    across SDK versions without importing private names.
    """

    #: The underlying HTTP response, whose body the caller has yet to read.
    http_response: Any

    def parse(self, *args: Any, **kwargs: Any) -> Any: ...


# Distinguishes "a body read owns finalization, stand down" from "no stream
# wrapper to finalize", which are both falsy but call for opposite handling.
_SUPPRESSED = object()


class _RawResponseProxyMeta(ABCMeta, type(_ObjectProxy)):
    """Metaclass compatible with wrapt's proxy type and ABC hooks."""


class RawResponseProxy(_ObjectProxy, metaclass=_RawResponseProxyMeta):
    """Proxy for a ``with_raw_response`` / ``with_streaming_response`` result.

    Wrapping the raw response (rather than the parsed payload) keeps every
    metadata attribute -- ``headers``, ``request_id``, ``http_response`` --
    resolving natively and keeps ``isinstance`` / ``__class__`` seeing the
    original type, while ``parse()`` routes on the value it returns:

    * a parsed payload the subclass recognizes -> extract response telemetry and
      finalize the invocation now;
    * a stream the subclass can wrap -> return an instrumented stream wrapper
      that finalizes the invocation when drained;
    * a coroutine (the async client's ``parse()``) -> return a coroutine that
      awaits it and dispatches by the same rules;
    * anything else -> return it untouched and log at debug.

    Routing on the parsed value rather than on the request headers is
    deliberate: the SDKs set ``x-stainless-raw-response: stream`` on every
    ``with_streaming_response`` call, streaming or not.

    The invocation is finalized independently of ``parse()``. A caller that
    never parses either reads the body directly (``read()``, ``.text``,
    ``.json()``) or abandons it, so hooks on the httpx response's ``read`` /
    ``aread`` and ``close`` / ``aclose`` finalize it when no dispatch did: the
    read hook with response attributes, the close hook with request attributes
    only.

    Only the instrumented stream wrapper is ever substituted for what the SDK
    returns. Every other ``parse()`` call is delegated, so the caller gets the
    SDK's own object with its cast target, post-parser, and per-target cache
    applied.

    Build instances through ``wrap_raw_response``: it decides between finalizing
    a completed response and arming this proxy's hooks on an open one.
    """

    def __init__(
        self,
        raw_response: RawResponse,
        invocation: GenAIInvocation,
    ) -> None:
        super().__init__(raw_response)
        self._self_invocation = invocation
        # The invocation is ours to end until a stream wrapper takes it over.
        self._self_span_open = True
        # Response telemetry is settled: whichever path saw the body first
        # recorded it (or gave up on it), so no later path may record again.
        self._self_dispatched = False
        # How many body reads are in flight, counting the ``parse()`` that
        # drives one. A read nested inside another -- the SDK's ``parse()``
        # reading the body is the common case -- must not finalize when the
        # inner one returns, so this is a depth rather than a flag.
        self._self_reads_in_flight = 0
        # The wrapper the close hook has to finalize when the caller abandons
        # the stream. Set by both the default and the cast parse.
        self._self_stream_wrapper: Any = None
        # The wrapper a repeated *default* ``parse()`` replays. Kept apart from
        # the field above so a ``parse(to=...)`` cannot serve its own cast
        # target to a later ``parse()`` that asked for the SDK's default type.
        self._self_replay_wrapper: Any = None

    # -- subclass hooks ----------------------------------------------------

    @abstractmethod
    def _extract_from_body(self, body: dict[str, object]) -> bool:
        """Record response telemetry from an already-read HTTP body.

        Called on the last path where the deserialized body is still available
        to telemetry: a caller that read the body without parsing it. Implement
        by constructing the SDK payload from ``body`` and applying it to the
        invocation, returning whether ``body`` was a payload this operation
        recognizes.

        Construct from ``body`` rather than calling the SDK's ``parse()``:
        running the caller's deferred parse would apply their cast target and
        post-parser, and populate the SDK's parse cache.

        Must not raise -- errors here would surface in place of the caller's own
        result.
        """

    @abstractmethod
    def _extract_from_parsed(self, parsed: object) -> bool:
        """Record response telemetry from the value ``parse()`` returned.

        Return ``True`` when ``parsed`` is the payload for this operation and
        telemetry was recorded, ``False`` to let the stream and fallback paths
        have a look. Must not raise.
        """

    @abstractmethod
    def _wrap_parsed_stream(self, parsed: object) -> object | None:
        """Return an instrumented wrapper for a parsed stream, or ``None``.

        ``None`` means "not a stream I can drive", which sends the value back to
        the caller untouched. Both the sync and the async stream type can reach
        either client's proxy, because the async client's legacy raw response
        returns an async stream from its *sync* ``parse()``.
        """

    # -- body-read and close hooks ----------------------------------------

    def _install_hooks(self, raw_response: RawResponse) -> None:
        http_response = getattr(raw_response, "http_response", None)
        if http_response is None:
            return
        # Stacking is safe: each hook calls the one it replaced, so two proxies
        # over one response finalize their own invocation in turn.
        for name, wrap in (
            ("read", self._wrap_sync_read),
            ("aread", self._wrap_async_read),
            ("close", self._wrap_sync_close),
            ("aclose", self._wrap_async_close),
        ):
            original = getattr(http_response, name, None)
            if original is not None:
                setattr(http_response, name, wrap(original))

    def _wrap_sync_read(
        self, original: Callable[..., Any]
    ) -> Callable[..., Any]:
        @functools.wraps(original)
        def _read(*args: object, **kwargs: object) -> Any:
            self._self_reads_in_flight += 1
            try:
                content = original(*args, **kwargs)
            finally:
                self._self_reads_in_flight -= 1
            self._finalize_read_fallback()
            return content

        return _read

    def _wrap_async_read(
        self, original: Callable[..., Awaitable[Any]]
    ) -> Callable[..., Awaitable[Any]]:
        @functools.wraps(original)
        async def _aread(*args: object, **kwargs: object) -> Any:
            self._self_reads_in_flight += 1
            try:
                content = await original(*args, **kwargs)
            finally:
                self._self_reads_in_flight -= 1
            self._finalize_read_fallback()
            return content

        return _aread

    def _finalize_read_fallback(self) -> None:
        """Finalize a response whose body the caller read without parsing.

        This is the last point at which the deserialized body is available to
        telemetry, so a caller that only ever reads is finalized here with full
        response attributes. A read still nested inside another -- the one
        ``parse()`` drives, most often -- is left alone: the outer read, or the
        dispatch that follows it, owns finalization.
        """
        if self._self_reads_in_flight or self._self_dispatched:
            return
        self._extract_body_of(getattr(self.__wrapped__, "http_response", None))
        # Settled either way: the invocation ends here, so a later ``parse()``
        # must not write into an already-stopped invocation.
        self._self_dispatched = True
        self._finalize_once()

    def _wrap_sync_close(
        self, original: Callable[..., object]
    ) -> Callable[..., object]:
        @functools.wraps(original)
        def _close(*args: object, **kwargs: object) -> object:
            try:
                return original(*args, **kwargs)
            finally:
                self._finalize_close_fallback()

        return _close

    def _wrap_async_close(
        self, original: Callable[..., Awaitable[object]]
    ) -> Callable[..., Awaitable[object]]:
        @functools.wraps(original)
        async def _aclose(*args: object, **kwargs: object) -> object:
            try:
                return await original(*args, **kwargs)
            finally:
                await self._afinalize_close_fallback()

        return _aclose

    def _take_stream_wrapper(self) -> Any:
        """The abandoned stream wrapper the close hook has to finalize, if any.

        httpx closes the response while it drains the body and only assigns the
        content afterwards, so a close that fires *during* a read -- including
        the read ``parse()`` drives -- would finalize with nothing to extract.
        The read owns finalization itself once the body is available.

        Handing the wrapper out clears it, which also breaks the recursion from
        finalizing it: closing the wrapper closes the SDK stream, which closes
        this same httpx response and re-enters the hook, where there is now no
        wrapper left and nothing to finalize.
        """
        if self._self_reads_in_flight:
            return _SUPPRESSED
        wrapper = self._self_stream_wrapper
        self._self_stream_wrapper = None
        return wrapper

    def _finalize_close_fallback(self) -> None:
        wrapper = self._take_stream_wrapper()
        if wrapper is _SUPPRESSED:
            return
        if wrapper is None:
            # Nothing read the body, so there are no response attributes to
            # recover; just end the invocation.
            self._finalize_once()
        elif is_async_stream_wrapper(wrapper):
            # Nothing here can await the wrapper; httpx also rejects a sync
            # close of an async response, so the ``aclose`` fallback is the one
            # that finalizes this stream.
            self._self_stream_wrapper = wrapper
            _logger.debug(
                "sync close of an async raw-response stream; leaving "
                "finalization to aclose"
            )
        else:
            self._close_stream_wrapper(wrapper)

    async def _afinalize_close_fallback(self) -> None:
        wrapper = self._take_stream_wrapper()
        if wrapper is _SUPPRESSED:
            return
        if wrapper is None:
            # Nothing read the body, so there are no response attributes to
            # recover; just end the invocation.
            self._finalize_once()
        elif is_async_stream_wrapper(wrapper):
            try:
                await wrapper.close()
            except Exception:  # pylint: disable=broad-exception-caught
                _logger.debug(
                    "error closing abandoned raw-response stream",
                    exc_info=True,
                )
        else:
            self._close_stream_wrapper(wrapper)

    def _close_stream_wrapper(self, wrapper: _Closable) -> None:
        try:
            wrapper.close()
        except Exception:  # pylint: disable=broad-exception-caught
            # ``close()`` finalizes the invocation with the error before
            # re-raising; the caller already abandoned this stream, so don't
            # surface it.
            _logger.debug(
                "error closing abandoned raw-response stream", exc_info=True
            )

    def _extract_body_of(self, http_response: Any) -> bool:
        """Decode an already-read body and hand it to the subclass."""
        body = _json_body(http_response)
        if body is None:
            return False
        return self._extract_from_body(body)

    def _finalize_once(self) -> None:
        # ``stop()`` is not idempotent, so finalize at most once.
        if self._self_span_open:
            self._self_span_open = False
            self._self_invocation.stop()

    # -- parse routing -----------------------------------------------------

    def parse(self, *args: Any, **kwargs: Any) -> object:
        # The SDK caches per cast target, so every call is delegated and the
        # caller always gets the SDK's own object -- with one exception, the
        # instrumented stream wrapper, which has to be handed back on repeat
        # calls or a second ``parse()`` would return the uninstrumented stream
        # over the same body. A ``parse(to=...)`` call asks for a different cast
        # target, so it is never served from that memo.
        if args or kwargs:
            parsed = self._sdk_parse(*args, **kwargs)
            if inspect.iscoroutine(parsed):
                return self._await_and_settle(parsed, self._settle_cast_parse)
            return self._settle_cast_parse(parsed)
        if self._self_replay_wrapper is not None:
            return self._replay(self._self_replay_wrapper)
        parsed = self._sdk_parse()
        if inspect.iscoroutine(parsed):
            return self._await_and_settle(parsed, self._dispatch)
        return self._dispatch(parsed)

    def _settle_cast_parse(self, parsed: object) -> object:
        """Record telemetry for a ``parse(to=...)`` and hand back its result.

        A cast parse asks for the caller's own target, so it is delegated and
        the caller gets the SDK's object -- with one exception. When the target
        is a stream (``parse(to=Stream[MyChunk])`` over an SSE body), it is
        wrapped: the wrapper is a transparent proxy, so the caller still sees
        their own type, and the invocation gets the streamed response
        attributes it would otherwise lose.

        Anything else did read the body, and that read suppressed the hook that
        would have recorded it, so replay that hook here.
        """
        if not self._self_dispatched:
            wrapped = self._wrap_parsed_stream_safely(parsed)
            if wrapped is not None:
                self._self_stream_wrapper = wrapped
                self._self_dispatched = True
                # The wrapper finalizes the invocation when drained or closed.
                self._self_span_open = False
                return wrapped
        if _body_was_read(getattr(self.__wrapped__, "http_response", None)):
            self._finalize_read_fallback()
        return parsed

    def _wrap_parsed_stream_safely(self, parsed: object) -> object | None:
        try:
            return self._wrap_parsed_stream(parsed)
        except Exception:  # pylint: disable=broad-exception-caught
            # A wrapper we failed to build must not turn the caller's
            # successful parse() into an error.
            _logger.debug(
                "failed to wrap a parsed raw-response stream; "
                "returning it uninstrumented",
                exc_info=True,
            )
            return None

    def _sdk_parse(self, *args: Any, **kwargs: Any) -> Any:
        # Count this as a read in flight only across an actual body read. The
        # sync ``parse()`` reads here, so guard this call; the async ``parse()``
        # only builds a coroutine and reads nothing until awaited, so
        # ``_await_and_settle`` counts the ``await`` instead. Counting outside a
        # body-read window would strand the depth above zero if the caller never
        # awaited the coroutine, leaking the invocation.
        self._self_reads_in_flight += 1
        try:
            return self.__wrapped__.parse(*args, **kwargs)
        except Exception:
            self._finalize_failed_parse()
            raise
        finally:
            self._self_reads_in_flight -= 1

    def _finalize_failed_parse(self) -> None:
        # The read that failed may already have closed the body, and the close
        # hook stood down while it ran, so nothing else will end this span.
        # Deserialization is the caller's own failure, not the API call's, so
        # the span stays a success -- just without response attributes.
        self._self_dispatched = True
        self._finalize_once()

    def _replay(self, value: object) -> object:
        if inspect.iscoroutinefunction(
            getattr(self.__wrapped__, "parse", None)
        ):
            return self._replay_async(value)
        return value

    async def _replay_async(self, value: object) -> object:
        return value

    async def _await_and_settle(
        self,
        awaitable: Awaitable[Any],
        settle: Callable[[Any], object],
    ) -> object:
        self._self_reads_in_flight += 1
        try:
            parsed = await awaitable
        except Exception:
            self._finalize_failed_parse()
            raise
        finally:
            self._self_reads_in_flight -= 1
        return settle(parsed)

    def _dispatch(self, parsed: object) -> object:
        if self._self_dispatched:
            # A read fallback already settled and ended this invocation; the
            # caller still gets the SDK's object, just without a second
            # recording.
            return parsed
        if self._extract_from_parsed(parsed):
            self._self_dispatched = True
            self._finalize_once()
            return parsed
        wrapped = self._wrap_parsed_stream_safely(parsed)
        if wrapped is not None:
            self._self_stream_wrapper = wrapped
            self._self_replay_wrapper = wrapped
            self._self_dispatched = True
            # The wrapper finalizes the invocation when it is drained or closed.
            self._self_span_open = False
            return wrapped
        # Neither a payload we recognize nor a stream we can drive; hand it back
        # untouched. The body was likely already read/closed during parse, so
        # finalize now with the request attributes.
        _logger.debug(
            "with_raw_response.parse() returned %s, which we cannot "
            "instrument; skipping response telemetry for this call",
            type(parsed).__name__,
        )
        self._self_dispatched = True
        self._finalize_once()
        return parsed


def _json_body(http_response: Any) -> dict[str, object] | None:
    """The response body as a JSON object, or ``None`` if it is not one.

    An SSE body, an empty body, or a JSON array all decode to ``None``; the
    caller treats that as "no payload to record".
    """
    if http_response is None:
        return None
    try:
        body: object = http_response.json()
    except Exception:  # pylint: disable=broad-exception-caught
        # Not JSON (an SSE stream is the routine case), so nothing to record.
        _logger.debug("raw-response body is not JSON")
        return None
    if not isinstance(body, dict):
        return None
    return cast("dict[str, object]", body)


def _body_was_read(http_response: Any) -> bool:
    """Whether the body is in memory; ``content`` raises until it has been read."""
    if http_response is None:
        return False
    try:
        http_response.content  # pylint: disable=pointless-statement
    except Exception:  # pylint: disable=broad-exception-caught
        # httpx raises ``ResponseNotRead``; catching broadly keeps this working
        # for any transport whose unread-body error we do not know.
        return False
    return True


def is_raw_response(result: object) -> bool:
    """Whether ``result`` is a raw-response object to route through the proxy.

    Matched on shape rather than on the SDKs' private response classes
    (``LegacyAPIResponse``, ``APIResponse``, ``AsyncAPIResponse``). The proxy
    needs both attributes: ``parse()`` to route on the parsed value and
    ``http_response`` to finalize the invocation for callers that never parse.
    """
    return hasattr(result, "parse") and hasattr(result, "http_response")


def wrap_raw_response(
    proxy_factory: Callable[[RawResponse], ProxyT],
    result: RawResponse,
    *,
    streamed: bool = False,
) -> ProxyT | RawResponse:
    """Wrap a ``with_raw_response`` / ``with_streaming_response`` result.

    A single payload the SDK has already read to completion is the whole
    operation: there is nothing left to defer to, and no further read or close
    will fire, so the invocation is finalized here -- whether or not the body
    turned out to be a payload the subclass recognizes, since leaving it open
    would leak the span -- and the caller gets its raw response untouched.

    ``streamed`` says the request asked for a stream, which the instrumentation
    knows from the call's own arguments. A streamed body is never treated as
    completed, however the transport reports it: buffered and mock transports
    hand back a closed response whose body is still a stream the caller has yet
    to ``parse()``. Sniffing the response instead would make routing depend on
    a ``content-type`` any gateway is free to rewrite.

    While the body is still open the caller owns when it is read, so the result
    is wrapped in the subclass's ``RawResponseProxy`` and the proxy's hooks are
    armed on the underlying HTTP response.
    """
    http_response = getattr(result, "http_response", None)
    completed = not streamed and getattr(http_response, "is_closed", False)
    proxy = proxy_factory(result)
    if completed:
        proxy._extract_body_of(http_response)
        proxy._self_dispatched = True
        proxy._finalize_once()
        return result
    proxy._install_hooks(result)
    return proxy


__all__ = [
    "RawResponse",
    "RawResponseProxy",
    "is_raw_response",
    "wrap_raw_response",
]
